# Generated by Django 5.1.5 on 2025-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujcovna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pujcka',
            name='Den_pujceni',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='pujcka',
            name='Den_vraceni',
            field=models.DateField(verbose_name=''),
        ),
    ]
