# Generated by Django 5.1.5 on 2025-04-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujcovna', '0002_alter_pujcka_den_pujceni_alter_pujcka_den_vraceni'),
    ]

    operations = [
        migrations.AddField(
            model_name='pujcka',
            name='auto',
            field=models.ForeignKey(default=1500, on_delete=django.db.models.deletion.CASCADE, related_name='pujcky', to='pujcovna.auto'),
            preserve_default=False,
        ),
    ]
