# Generated by Django 5.2 on 2025-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujcovna', '0003_pujcka_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pujcka',
            name='Den_pujceni',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pujcka',
            name='Den_vraceni',
            field=models.DateField(),
        ),
    ]
