# Generated by Django 5.1.5 on 2025-06-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujcovna', '0004_alter_pujcka_den_pujceni_alter_pujcka_den_vraceni'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='obrazky/'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Kategorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Motor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Palivo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Prevodovka',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Rok_vyroby',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='SPZ',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Vykon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='Znacka',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pujcka',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pujcovna.auto'),
        ),
        migrations.AlterField(
            model_name='pujcka',
            name='penize_za_den',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
